lib/sorbet-rails/model_rbi_formatter.rb, rbi/activerecord.rbi, spec/test_data/models/expected_potion.rbi, spec/test_data/models/expected_wand.rbi, spec/test_data/models/expected_wizard.rbi, spec/test_data/models/expected_wizard_wo_spellbook.rbi
Add signatures for ActiveRecord::Associations::CollectionProxy and
update generated model definitions for associations to use
CollectionProxy instead of Relation.
=> Add ActiveRecord::Associations::CollectionProxy

README.md
This is a lot more friendly. Under the hood, it is the same
https://github.com/sorbet/sorbet/blob/7e18aed84cdf7ca533eb26aa5cdc2e43aa604b4c/main/options/options.cc#L709
From sorbet documentation 
```
suggest-typed       Put the highest `typed:` sigil in each of your files
```
=> Use `srb rbi suggest-typed`

README.md, lib/sorbet-rails/model_rbi_formatter.rb, spec/test_data/v4.2/expected_potion.rbi, spec/test_data/v4.2/expected_spell_book.rbi, spec/test_data/v4.2/expected_wand.rbi, spec/test_data/v4.2/expected_wizard.rbi, spec/test_data/v4.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.0/expected_potion.rbi, spec/test_data/v5.0/expected_spell_book.rbi, spec/test_data/v5.0/expected_wand.rbi, spec/test_data/v5.0/expected_wizard.rbi, spec/test_data/v5.0/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.1/expected_potion.rbi, spec/test_data/v5.1/expected_spell_book.rbi, spec/test_data/v5.1/expected_wand.rbi, spec/test_data/v5.1/expected_wizard.rbi, spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.2/expected_potion.rbi, spec/test_data/v5.2/expected_spell_book.rbi, spec/test_data/v5.2/expected_wand.rbi, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi
Adds support for non-block `unscoped` method: https://apidock.com/rails/ActiveRecord/Scoping/Default/ClassMethods/unscoped
Unfortunately this method has also a less popular block option that has to be untyped as it can return anything so it has to be untyped.
=> ActiveRecord "unscoped" query method

lib/sorbet-rails/model_rbi_formatter.rb, lib/sorbet-rails/tasks/rails_rbi.rake, rbi/activerecord.rbi, spec/test_data/v4.2/expected_potion.rbi, spec/test_data/v4.2/expected_spell_book.rbi, spec/test_data/v4.2/expected_wand.rbi, spec/test_data/v4.2/expected_wizard.rbi, spec/test_data/v4.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.0/expected_potion.rbi, spec/test_data/v5.0/expected_spell_book.rbi, spec/test_data/v5.0/expected_wand.rbi, spec/test_data/v5.0/expected_wizard.rbi, spec/test_data/v5.0/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.1/expected_potion.rbi, spec/test_data/v5.1/expected_spell_book.rbi, spec/test_data/v5.1/expected_wand.rbi, spec/test_data/v5.1/expected_wizard.rbi, spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.2/expected_potion.rbi, spec/test_data/v5.2/expected_spell_book.rbi, spec/test_data/v5.2/expected_wand.rbi, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v6.0/expected_potion.rbi, spec/test_data/v6.0/expected_spell_book.rbi, spec/test_data/v6.0/expected_wand.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
Fix model rbi generation to work with sorbet 0.4.4366
Because sorbet generates hidden-definition.rbi file that contains the
following types of methods, they need to be put at the class leve
directly for sorbet to recognize the signature.
- Put associations in a model class directly
- Put enum-related methods in a model class directly
Note: we keep column methods in a separate modules because we haven't
supported serializer or attribute API. This allows people to override
the generated RBI
Fix using reflection.klass.name instead of reflection.class_name.
reflection.class_name is a user-input value when they define an
association, whereas reflection.klass.name reflects the ruby class that
Rails thinks the association should be
This also fix …
=> Fixes for sorbet 0.4.4366

lib/sorbet-rails/model_rbi_formatter.rb, lib/sorbet-rails/tasks/rails_rbi.rake, spec/test_data/v4.2/expected_wand.rbi, spec/test_data/v4.2/expected_wizard.rbi, spec/test_data/v4.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.0/expected_wand.rbi, spec/test_data/v5.0/expected_wizard.rbi, spec/test_data/v5.0/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.1/expected_wand.rbi, spec/test_data/v5.1/expected_wizard.rbi, spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.2/expected_wand.rbi, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v6.0/expected_wand.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
- Only uses models based on available classes. There was an instance of a model existed in the Const list, but `srb tc` doesn't see it. Better to keep the system correct internally.
- Force generating ActiveRecord::InternalMetadata and ActiveRecord::SchemaMigration because Sorbet starts generating those classes. If we don't generate those classes, `srb tc` will complain that they don't have `Elem` defined. `Rails.application.eager_load!` doesn't load them & I haven't found a way to load them reliably yet
- Generate ! method for enum values
=> More fixes to make sorbet-rails work out of the box

README.md
`srb init` now works with  when `sorbet-rails` is  in the gem file.
=> Remove instructions about adding sorbet-rails

lib/sorbet-rails/helper_rbi_formatter.rb, spec/test_data/v4.2/expected_helpers.rbi, spec/test_data/v5.0/expected_helpers.rbi, spec/test_data/v5.1/expected_helpers.rbi, spec/test_data/v5.2-no-sorbet/expected_helpers.rbi, spec/test_data/v5.2/expected_helpers.rbi, spec/test_data/v6.0/expected_helpers.rbi
`ActionView::Helpers` provides methods like `link_to` in Helpers, e.g. I have a helper like this:
```ruby
module GamesHelper
def sort_dropdown_link(sort, humanized_name)
link_to(humanized_name, request.params.merge(order_by: nil), class: "dropdown-item#{params[:order_by].nil? ? ' has-text-weight-bold' : ''}")
end
end
```
Previously, the `link_to` and `request` methods were undefined according to Sorbet. With this change, this code no longer throws Sorbet errors :)
I had hoped to also figure out how to include the URL methods (e.g. `user_url`) in Helpers, but I think the way sorbet-rails currently implements those methods is somewhat flawed (or perhaps I'm misunderstanding how it actually works in Rails?), since I haven't been able to figure out a way to include those methods as part of …
=> Include ActionView::Helpers in helpers.rbi

lib/sorbet-rails/tasks/rails_rbi.rake, spec/support/v4.2/sorbet/rbi/hidden-definitions/hidden.rbi, spec/support/v5.0/sorbet/rbi/hidden-definitions/hidden.rbi, spec/support/v5.1/sorbet/rbi/hidden-definitions/hidden.rbi, spec/support/v5.2/sorbet/rbi/hidden-definitions/hidden.rbi, spec/support/v6.0/sorbet/rbi/hidden-definitions/hidden.rbi
- In Rails 6.0, there are dynamic classes like "primary::SchemaMigration". When we try to generate rbi for this class, sorbet will complain that we shouldn't use dynamic class. We ignore them because it's unlikely anyone will use them.
- Update hidden-definition to avoid conflict with newer version of Sorbet.
=> Fix primary::SchemaMigration in Rails 6.0 & sorbet version upgrade

spec/bin/run_spec.sh
1. Add 'DISABLE_DATABASE_ENVIRONMENT_CHECK=1' twice to sorbet-rails/spec/bin/run_spec.sh file. This fix gets rid of these messages:
```
ActiveRecord::NoEnvironmentInSchemaError:
Environment data not found in the schema. To resolve this issue, run:
bin/rails db:environment:set RAILS_ENV=test
```
=> Fix ActiveRecord::NoEnvironmentInSchemaError message

lib/sorbet-rails/tasks/rails_rbi.rake
And instead of saving a blank `helpers.rbi` file, just output a log message.
Fixes #120.
=> Fix helpers task throwing a NoMethodError when there are no helpers.

CONTRIBUTING.md, Rakefile
This was one of the requested improvements from #117. Pretty simple fix.
You can test it by pulling down the branch, changing something in `spec/generators/sorbet_test_cases.rb` and then running `bundle exec rake update_spec:sorbet_test_cases`.
=> Add a Rake task for copying sorbet_test_cases.rb into all the spec/support/ apps

.gitignore, lib/sorbet-rails/activerecord.rbi, lib/sorbet-rails/config.rb, lib/sorbet-rails/model_plugins/active_record_assoc.rb, lib/sorbet-rails/model_plugins/active_record_attribute.rb, lib/sorbet-rails/model_plugins/active_storage_methods.rb, lib/sorbet-rails/model_plugins/plugins.rb, spec/generators/rails-template.rb, spec/model_rbi_formatter_spec.rb, spec/support/v4.2/app/models/wizard.rb, spec/support/v5.0/app/models/wizard.rb, spec/support/v5.1/app/models/wizard.rb, spec/support/v5.2/app/models/wizard.rb, spec/support/v6.0/app/models/wizard.rb, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v6.0/expected_blob.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
Also made some small formatting changes in a few places.
Fixes #148.
`attachment_reflections` wasn't added until 6.0, with https://github.com/rails/rails/pull/33018
So this doesn't support 5.2, and I'm not sure of a good way to get it to work. We can do something like `User.reflect_on_all_associations.filter { |x| x.name.to_s.end_with?('attachment') }`, but that's _really_ gross so I don't want to.
Are we fine just having this only support 6.0?
=> Add ActiveStorage attachment methods

sorbet-rails.gemspec
To release `require_typed`, `fetch_typed` and recent small fixes, and a breaking change coming from sorbet
=> Preparing 0.5.5

lib/sorbet-rails/model_plugins/active_record_enum.rb
@wpride reported that sometimes `enum_call` could be nil for models. I'm unable to reproduce it but it's a good idea to be defensive around accessing nilable object.
cc @deecewan
=> Check enum_call nil before proceeding

lib/sorbet-rails.rb, lib/sorbet-rails/custom_types/boolean_string.rb, lib/sorbet-rails/custom_types/integer_string.rb, spec/boolean_string_spec.rb, spec/integer_string_spec.rb
It's common in Rails to have IntegerString passed in from the client side. It may be convenient to be able to check that a string is an IntegerString, but not a random string. Idea suggested by @twhitnah :-)
=> Introduce IntegerString & BooleanString class to typecheck input params

lib/sorbet-rails/helper_rbi_formatter.rb, lib/sorbet/rbi/todo.rbi, spec/support/v4.2/Gemfile.lock, spec/support/v5.0/Gemfile.lock, spec/support/v5.1/Gemfile.lock, spec/test_data/v5.0/expected_helpers.rbi, spec/test_data/v5.0/expected_helpers_with_application_and_devise_helpers.rbi, spec/test_data/v5.1/expected_helpers.rbi, spec/test_data/v5.1/expected_helpers_with_application_and_devise_helpers.rbi, spec/test_data/v5.2/expected_helpers.rbi, spec/test_data/v5.2/expected_helpers_with_application_and_devise_helpers.rbi, spec/test_data/v6.0/expected_helpers.rbi, spec/test_data/v6.0/expected_helpers_with_application_and_devise_helpers.rbi
Resolves #156.
This intentionally does not include DeviseHelper because you can pass any kind of module into the `includes` config, and I don't think the Devise helpers are included in `helpers` anyway.
It checks for the existence of the `helpers` method because the method doesn't exist on 4.2.
=> Add helpers method

README.md, sorbet-rails.gemspec, spec/support/v4.2/Gemfile.lock, spec/support/v5.0/Gemfile.lock, spec/support/v5.1/Gemfile.lock, spec/support/v6.0/Gemfile.lock
- Release the recent additions as a new version
- Add deprecation notice while we're still working on v0.6
- Create a branch that can be used to release fixes for Rails 4.2 in the future (if anyone need it)
=> Release a final version with v4.2

README.md
Hi there, I found typo on link to config.rb file, the typo is :
- before : https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/lib/sorbet-rails/config.rb 
- should be : https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/config.rb
=> Fix Typo link to file config.rb in the README.md

README.md
Maybe this is overzealous, but we got really burned by it. We were using `sorbet-rails` in development only, but `sorbet-runtime` in all environments. This meant we were able to access `X::ActiveRecord_Relation` in development, and thus someone used that in a method signature. When we deployed this code it failed in production because [this railtie](https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/railtie.rb#L30) didn't run, so the constant was still private.
Adding a warning so it doesn't happen to other people.
=> Add warning about using with `sorbet-runtime`

lib/sorbet-rails/sorbet_utils.rb, spec/sorbet_utils_spec.rb
This fixes it when there are method with missing parameter name:
```
def method_with_missing_args_name(p1, *); end
def method_with_missing_kwargs_name(p1, **); end
```
=> fix sorbet_util: extract params when param doesn't have name

README.md, lib/sorbet-rails/tasks/rails_rbi.rake, spec/rake_rails_rbi_models_spec.rb
When using STI in rails with a large number of descendant models, it's frustrating when I update the parent class because I have two options:
1. Re-run the entire `rake rails:models_rbi` script, which is slow.
2. Enumerate all child models manually and make a really long command like `rake rails:models_rbi[Foo,Bar,Bax,Asdf,Etc]`
This changes the default to *include* descendants of a model when its specified as a specific argument. Then I only need to do `rake rails:models_rbi[Parent]` to regenerate all children.
I think this makes sense because I can't really imagine a scenario where the parent changes but we would not want to also be safe and regenerate the children.
=> Regenerate descendants of specific models

lib/sorbet-rails/model_plugins/active_record_assoc.rb
Follow-up to https://github.com/chanzuckerberg/sorbet-rails/pull/206
```
> reflection.options
=> {:inverse_of=>:payment_intents, :optional=>false}
```
```
> reflection.options[:optional].present?
=> false
```
```
> reflection.options.key?(:optional)
=> true
```
=> Fix bug with usage of `present?`

lib/sorbet-rails/routes_rbi_formatter.rb, spec/test_data/v5.0/expected_routes.rbi, spec/test_data/v5.1/expected_routes.rbi, spec/test_data/v5.2/expected_routes.rbi, spec/test_data/v6.0/expected_routes.rbi
Routes are accessible in Mailers by default (both the Mailer class and the relevant view).
https://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views doesn't explicitly confirm this, but I tested in a brand new Rails app and it worked as expected.
=> Include Routes in Mailers

lib/sorbet-rails/tasks/rails_rbi.rake
Dearest Reviewer,
I hope all is well this November.  It as been a long month for me and I look forward to the amazing things sorbet will help me with. I have interface classes that raise NotImplementedError and the model process is dying on it. I have found locally this to be an acceptable change. I hope that you agree. 
Changes
Add NotImplementedError to the model processing exception handling for interface like classes.
To reproduce add a method that raises NotImplementedError. 
Becker
=> Handle NotImplementedError raises

lib/sorbet-rails/model_plugins/active_record_assoc.rb, spec/generators/rails-template.rb, spec/model_rbi_formatter_spec.rb, spec/support/v5.0/Gemfile, spec/support/v5.0/Gemfile.lock, spec/support/v5.0/app/models/potion.rb, spec/support/v5.1/Gemfile, spec/support/v5.1/Gemfile.lock, spec/support/v5.1/app/models/potion.rb, spec/support/v5.2/Gemfile, spec/support/v5.2/Gemfile.lock, spec/support/v5.2/app/models/potion.rb, spec/support/v6.0/Gemfile, spec/support/v6.0/Gemfile.lock, spec/support/v6.0/app/models/potion.rb, spec/test_data/v5.0/expected_potion.rbi, spec/test_data/v5.1/expected_potion.rbi, spec/test_data/v5.2/expected_potion.rbi, spec/test_data/v6.0/expected_potion.rbi
@ghiculescu found a bug related to `belongs_to_and_required` return `nil` instead of T::Boolean. I fix it, but I also feel that this method, or methods that return T::Boolean should probably return T.nilable(T::Boolean), because it's very common in ruby/rails to return `nil` for boolean-y functions. Mmmm
=> Fix belongs to and required returns nil

lib/bundled_rbi/active_record_relation.rbi
`any?` is the opposite of ... https://github.com/rails/rails/blob/6-0-stable/activerecord/lib/active_record/relation.rb#L265-L268
=> Add ActiveRecord::Relation#empty?

README.md
=> Fix typo in README under the "Controllers" header detailing typed params

lib/sorbet-rails/utils.rb
Ufuk recommended it here. It seems to apply to Rails 6 only, but seems like a useful addition
https://sorbet-ruby.slack.com/archives/CJL5B3CEN/p1579907256019200?thread_ts=1579233124.001100&cid=CJL5B3CEN
=> Use Rails.autoloaders to eagerload more stuff in Rails 6

README.md, lib/sorbet-rails/rails_mixins/generated_url_helpers.rb, lib/sorbet-rails/railtie.rb, spec/generators/sorbet_test_cases.rb, spec/support/v5.0/sorbet_test_cases.rb, spec/support/v5.1/sorbet_test_cases.rb, spec/support/v5.2/sorbet_test_cases.rb, spec/support/v6.0/sorbet_test_cases.rb
It is a common problem for adopters to run into 4002 issue with 
```
include Rails.application.routes.url_helpers
```
We already have GeneratedUrlHelpers that encapsulate the signature for url_helper methods. It's easy to add implementation and make it a replacement for the dynamic module.
=> Add generated url helpers implementation

lib/bundled_rbi/active_record_relation.rbi, lib/bundled_rbi/pluck_to_tstruct.rbi
Let's test if we need to define Elem in ActiveRecord::Relation. We already set a fixed one in every subclass we generate.
=> Fix Elem to T.untyped in ActiveRecord::Relation 

lib/sorbet-rails/typed_params.rb, sorbet-rails.gemspec
The new version of sorbet-coerce supports
- `T::Set`
- `T.untyped`
Also, it renames `T::Coerce` to `TypeCoerce` since sorbet is planning to lock the `T` namespace.
=> Upgrade sorbet-coerce to v0.2.3

lib/sorbet-rails.rb
I am playing with this on `master`, and get an uninitialized constant error without this (or an explicit require in my app).
If this is not the right place for this let me know and I'll move it.
=> Add require for typed_params

lib/sorbet-rails/type_assert/type_assert.rb
Placing the whole declaration of `TypeAssertImpl` in a `typed: ignore` file hides the definition from tools like `tapioca`, since they also use `sorbet` internally to discover symbols.
Since Ruby can reopen classes/modules, there is no harm in adding an empty declaration of the module at the top level even if the concrete type was not loaded.
=> Make `TypeAssertImpl` visible even if concrete type cannot be loaded

lib/sorbet-rails/model_plugins/active_record_attribute.rb, spec/generators/rails-template.rb, spec/support/v5.0/app/models/wizard.rb, spec/support/v5.1/app/models/wizard.rb, spec/support/v5.2/app/models/wizard.rb, spec/support/v6.0/app/models/wizard.rb, spec/test_data/v5.0/expected_spell_book.rbi, spec/test_data/v5.0/expected_wand.rbi, spec/test_data/v5.0/expected_wizard.rbi, spec/test_data/v5.0/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.1/expected_spell_book.rbi, spec/test_data/v5.1/expected_wand.rbi, spec/test_data/v5.1/expected_wizard.rbi, spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.2/expected_spell_book.rbi, spec/test_data/v5.2/expected_wand.rbi, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v6.0/expected_spell_book.rbi, spec/test_data/v6.0/expected_wand.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
For `T::Enum` enums generated from rails enums, use `%q{}` instead of
`''` so that enums with single-quotes won't break sorbet-rails
Also added a test case which before generated a bunch of errors and now works
=> Use percent-string instead of single quotes

lib/sorbet-rails/active_record_rbi_formatter.rb, spec/generators/sorbet_test_cases.rb, spec/support/v5.0/sorbet_test_cases.rb, spec/support/v5.1/sorbet_test_cases.rb, spec/support/v5.2/sorbet_test_cases.rb, spec/support/v6.0/sorbet_test_cases.rb, spec/test_data/v5.0/expected_active_record_base.rbi, spec/test_data/v5.0/expected_active_record_relation.rbi, spec/test_data/v5.1/expected_active_record_base.rbi, spec/test_data/v5.1/expected_active_record_relation.rbi, spec/test_data/v5.2/expected_active_record_base.rbi, spec/test_data/v5.2/expected_active_record_relation.rbi, spec/test_data/v6.0/expected_active_record_base.rbi, spec/test_data/v6.0/expected_active_record_relation.rbi
- Add more assertions to the `sorbet_test_cases.rb`. Most have been commented out since sorbet-rails doesn't currently support them.
- Minor updates to `ActiveRecordRbiFormatter` to support some of the new assertions.
This is the first of a few PRs that I'll be spinning out of #308 to make it easier/possible to review.
=> Add more sorbet test cases

lib/sorbet-rails/active_record_rbi_formatter.rb, spec/generators/sorbet_test_cases.rb, spec/support/v5.0/sorbet_test_cases.rb, spec/support/v5.1/sorbet_test_cases.rb, spec/support/v5.2/sorbet_test_cases.rb, spec/support/v6.0/sorbet_test_cases.rb, spec/test_data/v5.0/expected_active_record_base.rbi, spec/test_data/v5.0/expected_active_record_relation.rbi, spec/test_data/v5.1/expected_active_record_base.rbi, spec/test_data/v5.1/expected_active_record_relation.rbi, spec/test_data/v5.2/expected_active_record_base.rbi, spec/test_data/v5.2/expected_active_record_relation.rbi, spec/test_data/v6.0/expected_active_record_base.rbi, spec/test_data/v6.0/expected_active_record_relation.rbi
Follow-up to #311. Generates RBI for `build`, `first_or_create`, `first_or_create!`, `first_or_initialize`.
NOTE: The first 3 commits here are from that branch, they'll go away once that is merged and I rebase.
=> Generate sigs for more build/create ActiveRecord methods

spec/generators/sorbet_test_cases.rb, spec/sorbet_spec.rb, spec/support/v5.0/sorbet_test_cases.rb, spec/support/v5.0/typed-override.yaml, spec/support/v5.1/sorbet_test_cases.rb, spec/support/v5.1/typed-override.yaml, spec/support/v5.2/sorbet_test_cases.rb, spec/support/v5.2/typed-override.yaml, spec/support/v6.0/sorbet_test_cases.rb, spec/support/v6.0/typed-override.yaml
From this commit (https://github.com/chanzuckerberg/sorbet-rails/commit/14047ab3bade0ae5d74f93f5bcfde7064741192c) it appears the typed-override was used to prevent issues where `srb init` was setting `sorbet_test_cases.rb` to `typed: false`. I was running into the opposite issue where it was turning it from false to true. When that happens, `srb tc` would fail because it was raise an error saying we were using an unnecessary override.
This PR ensures `sorbet_test_cases.rb` is set to `typed: true` but does so via `gsub`.
=> Remove usage of typed override in tests

lib/sorbet-rails/custom_types/boolean_string.rb, lib/sorbet-rails/custom_types/integer_string.rb, lib/sorbet-rails/deprecation.rb, lib/sorbet-rails/rails_mixins/custom_params_methods.rb
I think `TypedParams` provide a much neater API to do all conversion at once. It also helps converting boolean string or integer string to native ruby type.
Plus, we found through profiling that BooleanString and IntegerString incurs some cost in type-checking String, even when they are not used directly. This deprecation will help us getting rid of them as well.
Slated to remove them by v0.7, but issue a warning for now.
Test plan: spec shows the warning now!
=> [deprecation] add deprecation warning for fetch_typed, etc.

lib/sorbet-rails/model_plugins/active_record_named_scope.rb, lib/sorbet-rails/tasks/rails_rbi.rake
This PR does two things that improve performance and memory usage:
- Write the model RBI after each loop. Previously we were generating all the model RBIs and storing the strings inside of an array and then once we generated it all we were writing it out to files. This is pretty inefficient from a memory perspective which likely leads to a performance hit as well.
- Speed up the `ActiveRecordNamedScope` plugin. I instrumented the plugins (just took `Time.now` before and after and printed it out) and was getting an average of ~4.5s for the ActiveRecordNamedScope. I found the culprit (`method_obj.owner.name` was very expensive for some reason 🤷) and took the time down to an average of 0.03s 🔥.
I ran this against my company's codebase with ~750 models.
**Before**
Using `0.6.3` I actually …
=> Improve performance of model RBI generation

lib/sorbet-rails/model_plugins/base.rb
Recent version of sorbet-rails added a neat optimization to make
attributes non nilable if they had an "unconditional validation".
After updating we had some parts of the code report wrongly unreachable code.
This is becase we have some validations using `:on` which are detected
– wrongly – as unconditional.
Didn't add any test since I saw that only the `:if` clause was actually
tested.
=> Stop infering `validate :on` as unconditional

lib/sorbet-rails/model_plugins/active_record_assoc.rb
I had a model with associations like:
```
has_many :liabilities
has_many :payroll_taxes, through: :liabilities, source: :liability, source_type: 'PayrollTax'
```
This means that payroll_taxes is a "has many through" association where the join table is polymorphic so sorbet-rails was generating:
```ruby
sig { returns(ActiveRecord::Associations::CollectionProxy) }
def payroll_taxes; end
```
I would expect:
```ruby
sig { returns(::PayrollTax::ActiveRecord_Associations_CollectionProxy) }
def payroll_taxes; end
```
This was because it was using logic when checking if the reflection was polymorphic that said "is this a has-many-through? then check if the join table is polymorphic". I don't quite get that logic. In this case it shouldn't matter that the join table is polymorphic (in fact, I …
=> Loosen assoc_should_be_untyped check

.travis.yml, lib/sorbet-rails/active_record_rbi_formatter.rb, lib/sorbet-rails/model_plugins/active_storage_methods.rb, lib/sorbet-rails/model_utils.rb, spec/test_data/v6.0/expected_active_record_relation.rbi, spec/test_data/v6.0/expected_blob.rbi, spec/test_data/v6.0/expected_routes.rbi, spec/test_data/v6.0/expected_spell_book.rbi, spec/test_data/v6.0/expected_squib.rbi, spec/test_data/v6.0/expected_wand.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
- The build/create/create!/new method on ActiveRecord Relation now use a new sig
- Force generating named scope methods in Rails 6
- Fix sig with active_storage: attachables shouldn't have *
- Regenerate routes.rbi for Rails 6.
- Disable test for Ruby 2.7, Rails 6 due to a RBI generation error: https://github.com/sorbet/sorbet/issues/2994
=> fix spec failures in rails 6

sorbet/rbi/hidden-definitions/hidden.rbi
new build failure due to new signature for OpenSSL::PKey::RSA#sign_pss and OpenSSL::PKey::RSA#verify_pss
=> fix build due to a new version of sorbet

lib/bundled_rbi/typed_enum.rbi, lib/sorbet-rails/tasks/rails_rbi.rake
Previously we relied on hidden-definitions to add this method. It's better to provide our own so in case people haven't run hidden-definitions or don't run hidden-definitions, it is still recognized.
=> add a bundled typed_enum.rbi

lib/sorbet-rails/rails_mixins/generated_url_helpers.rb, spec/generators/sorbet_test_cases.rb, spec/support/v5.0/sorbet_test_cases.rb, spec/support/v5.1/sorbet_test_cases.rb, spec/support/v5.2/sorbet_test_cases.rb, spec/support/v6.0/sorbet_test_cases.rb
Turns out classes including `url_helpers` does not need `default_url_options` defined explicitly to work (See #335). This PR implements a `default_url_options` method that draw it from the Rails application config so that people don't have to implement it explicitly.
Note that the default for `Rails.application.config` is {} and usually applications will set it for their mailer etc. The `_path` methods will work empty options {} but the `_url` methods still require a valid set of options with a HOST.
=> Add default url options to url helpers

sorbet-rails.gemspec, spec/support/v5.0/Gemfile.lock, spec/support/v5.1/Gemfile.lock, spec/support/v5.2/Gemfile.lock, spec/support/v6.0/Gemfile.lock
- Drop "fetch_typed", "require_typed" in favor of TypedParams
- Drop "IntegerString", "BooleanString" because they are not needed with TypedParams. They also introduce unnecessary perf cost.
- Add a sig for typed_enum.
- Fix GeneratedUrlHelper working with _path method out of the box.
=> release 0.7.0

README.md, lib/sorbet-rails/model_plugins/active_record_attribute.rb, spec/test_data/v5.0/expected_spell_book.rbi, spec/test_data/v5.0/expected_wand.rbi, spec/test_data/v5.0/expected_wizard.rbi, spec/test_data/v5.0/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.1/expected_spell_book.rbi, spec/test_data/v5.1/expected_wand.rbi, spec/test_data/v5.1/expected_wizard.rbi, spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi, spec/test_data/v5.2/expected_spell_book.rbi, spec/test_data/v5.2/expected_wand.rbi, spec/test_data/v5.2/expected_wizard.rbi, spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi, spec/test_data/v6.0/expected_spell_book.rbi, spec/test_data/v6.0/expected_wand.rbi, spec/test_data/v6.0/expected_wizard.rbi, spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
In one of our apps, we have this ... unfortunate ... enum setup.
```ruby
class RosterTemplate < ApplicationRecord
enum template_type: {
"RosterTemplate": 0,
}
end
```
sorbet-rails generates this rbi:
```ruby
class RosterTemplate::TemplateType < T::Enum
enums do
RosterTemplate = new(%q{RosterTemplate})
end
end
```
sorbet doesn't like that:
```
sorbet/rails-rbi/models/roster_template.rbi:140: Unable to resolve constant TemplateType https://srb.help/5002
140 |class RosterTemplate::TemplateType < T::Enum
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The error message isn't very clear, but we are 99% sure it's because `RosterTemplate` is both the model class, _and_ one of the enum value types.
We've found that tweaking the sorbet-rails generated rbi to this fixes the issue:
```ruby
class RosterTemplate …
```
=> Generate`T::Enum`s as a nested class

lib/sorbet-rails/model_plugins/active_record_assoc.rb
Given the primary key for a table is not always "id", use reflection.class.primary_key instead.
I noticed this due to having two tables in my application with non-standard primary keys (Sadly they are very hard to change).
NOTE: I have not added a test for this since I'm not sure what would be most appropriate. I started changing "spell_books" to have a primary key of "spell_id" (in only rails v5.2 - and guessing you would want all versions changed). However, I figured it was better to ask for the preferences of the maintainers before continuing with more work.
=> fix: primary key is not always "id"

lib/sorbet-rails/rails_mixins/pluck_to_tstruct.rb, spec/pluck_to_tstruct_spec.rb, spec/tstruct_comparable.rb
Consider this scenario
```ruby
class TUserStruct < T::Struct
const :id, Integer
const :name, String, default: "Unknown"
end
User.create!(name: nil)
User.all.pluck_to_tstruct(TA[TUserStruct].new)
```
This PR makes it so that in this case `pluck_to_tstruct` will use the default value for the `name` prop ("Unknown") instead of throwing a type error
I decided to only allow this behaviour if the type isn't nilable because if the type is nilable then I assume we'd be explicitly saying we don't want to use the default in that case I guess? Keen for thoughts
=> pluck_to_tstruct - Use tstruct prop's default value if type isn't nilable and the plucked value is nil

lib/sorbet-rails/tasks/rails_rbi.rake
One of my teammate found that `modules_for_helpers` is actually defined twice: one in 
`AbstractControler::Helpers` and override in `ActionController::Helpers`. The behavior
we rely on, `modules_for_helpers[:all]` is only defined in `ActionController::Helpers`.
We should check explicitly that this override is supported by checking that ApplicationController
includes ActionController::Helpers
=> check ApplicationController include ActionController::Helpers explicitly

README.md
If I have multiple rails project
`srb rbi xxx` won't work
=> Doc: add `bundle exec` to example srb command

lib/sorbet-rails/gem_plugins/kaminari_plugin.rb
This PR adds the [`last_page?`](https://github.com/kaminari/kaminari/blob/c5186f5d9b7f23299d115408e62047447fd3189d/kaminari-core/lib/kaminari/models/page_scope_methods.rb#L82) method to the `kaminari_plugin.rb` file. This method didn't seem to fit with the pattern of the other methods generated by `add_relation_query_method`, since it does not return a `Model::RelationType` (can't chain). Not sure if this is the best way to generate this method, but I added generators for `Model::ActiveRecord_Relation`, `Model::ActiveRecord_AssociationRelation`, and `Model::ActiveRecord_Associations_CollectionProxy`
=> add `last_page?` method to kaminari plugin

lib/sorbet-rails/job_rbi_formatter.rb
This was referencing mailers in the output when its really about jobs.
=> Fix typo in job_rbi_formatter

lib/sorbet-rails/model_rbi_formatter.rb
The current message is easy to miss. This hopefully draws more attention to it. It now looks like this:
```
$ bundle exec rake rails_rbi:models[Foo]
Note: Unable to create new instance of Foo
Got a ActiveRecord::StatementInvalid, with this message: PG::UndefinedTable: ERROR:  relation "foos" does not exist
LINE 8:  WHERE a.attrelid = '"foos"'::regclass
^
-- Generate sigs for Foo --
```
=> Better error if not able to initialize model

lib/sorbet-rails/gem_plugins/aasm_plugin.rb
This is an enhancement to the AASM gem plugin.
The AASM gem [auto-generates constants](https://github.com/aasm/aasm#auto-generated-status-constants) for each AASM status. Currently, the plugin does not account for this, so Sorbet is unable to resolve these auto-generated constants. This PR adds that functionality.
=> Create modules for AASM auto generated status constants

.github/workflows/publish-gem.yml, README.md, sorbet-rails.gemspec
Reverts https://github.com/chanzuckerberg/sorbet-rails/pull/465
While this gem's maintenance status is unclear, I'm not sure this is a great idea.
Additionally, using `ENV['GITHUB_RUN_NUMBER']` in the gemspec made it not possible to use this gem using a github ref in your gemfile.
=> Disable autoreleases on master

lib/sorbet-rails/tasks/rails_rbi.rake
When Rails projects are initialized without certain components, say without ActiveRecord, `bundle exec rake rails_rbi:all` will fail.
- Start a new rails project
- `rails new test --skip-active-record`
- Install sorbet-rails
- `bundle exec rake rails_rbi:all`
```
rake aborted!
NameError: uninitialized constant ActiveRecord
Did you mean?  ActiveModel
/Users/dxd/sorbet-rails/lib/sorbet-rails/tasks/rails_rbi.rake:66:in `block (2 levels) in <main>'
/Users/dxd/sorbet-rails/lib/sorbet-rails/tasks/rails_rbi.rake:20:in `block (2 levels) in <main>'
/Users/dxd/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/dxd/.rvm/rubies/ruby-3.0.0/bin/bundle:23:in `load'
/Users/dxd/.rvm/rubies/ruby-3.0.0/bin/bundle:23:in `<main>' …
```
=> [Fix] Skip missing active-records components

lib/sorbet-rails/model_plugins/active_record_querying.rb, spec/support/v7.0/Gemfile.lock, spec/support/v7.0/sorbet_test_cases.rb, spec/test_data/v7.0/expected_attachment.rbi, spec/test_data/v7.0/expected_blob.rbi, spec/test_data/v7.0/expected_headmaster.rbi, spec/test_data/v7.0/expected_internal_metadata.rbi, spec/test_data/v7.0/expected_potion.rbi, spec/test_data/v7.0/expected_record.rbi, spec/test_data/v7.0/expected_robe.rbi, spec/test_data/v7.0/expected_schema_migration.rbi, spec/test_data/v7.0/expected_school.rbi, spec/test_data/v7.0/expected_spell.rbi, spec/test_data/v7.0/expected_spell/habtm_spell_books.rbi, spec/test_data/v7.0/expected_spell_book.rbi, spec/test_data/v7.0/expected_spell_book/habtm_spells.rbi, spec/test_data/v7.0/expected_squib.rbi, spec/test_data/v7.0/expected_subject.rbi, spec/test_data/v7.0/expected_subject/habtm_wizards.rbi, spec/test_data/v7.0/expected_variant_record.rbi, spec/test_data/v7.0/expected_wand.rbi, spec/test_data/v7.0/expected_wizard.rbi, spec/test_data/v7.0/expected_wizard/habtm_subjects.rbi, spec/test_data/v7.0/expected_wizard_wo_spellbook.rbi
https://api.rubyonrails.org/v7.0.0/classes/ActiveRecord/QueryMethods.html#method-i-in_order_of
=> Add support for `ActiveRecord::QueryMethods#in_order_of`
