chanzuckerberg/sorbet-rails

- spec/bin/reset_test_data.sh
- spec/bin/run_all_specs.sh
Add scripts to make it easy to run tests & reset test data
> Script to run tests

- spec/support/5.2.3/db/migrate
> fix spec/support/5.2.3/db/migrate symlink

- lib/sorbet-rails/model_rbi_formatter.rb
old code I had from the original version
> remove deadcode

- lib/sorbet-rails/model_rbi_formatter.rb
- spec/test_data/v5.1/expected_wand.rbi
- spec/test_data/v5.1/expected_wizard.rbi
- spec/test_data/v5.1/expected_wizard_wo_spellbook.rbi
- spec/test_data/v5.2/expected_wand.rbi
- spec/test_data/v5.2/expected_wizard.rbi
- spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi
found out that Rails actually add <column_name?> method for all columns.
> generate column_name? method for all columns in a model

- CONTRIBUTING.md
Makes it easier for people to debug.
> Add a section on Debugging to CONTRIBUTING.md

- lib/sorbet-rails/routes_rbi_formatter.rb
- spec/test_data/v4.2/expected_no_routes.rbi
- spec/test_data/v5.0/expected_no_routes.rbi
- spec/test_data/v5.1/expected_no_routes.rbi
- spec/test_data/v5.2/expected_no_routes.rbi
- spec/test_data/v6.0/expected_no_routes.rbi
> clean up no routes

- lib/sorbet-rails/custom_finder_methods.rb
- sorbet-rails.gemspec
- spec/custom_finder_methods_spec.rb
- spec/rails_helper.rb
- spec/support/rails_shared/app/models/wizard.rb
- spec/support/v5.2/Gemfile.lock
- spec/support/v5.2/config/environments/development.rb
- spec/support/v5.2/db/schema.rb
- Fix a bug that find_n should be able to accept variable length arguments
- Add tests that test first_n, last_n and find_n
> Add tests for custom finder methods & fix a bug.

- sorbet-rails.gemspec
> Change Gem version to 0.3.0

- rbi/activerecord.rbi
I requested it in sorbet-typed for a while but it's not merged yet
https://github.com/sorbet/sorbet-typed/pull/36
> Active model dirty

- CONTRIBUTING.md
> Add information about sorbet `srb tc` test cases

- .travis.yml
- spec/support/v4.2/sorbet/rbi/hidden-definitions/hidden.rbi
- spec/support/v5.0/sorbet/rbi/hidden-definitions/hidden.rbi
- spec/support/v5.1/sorbet/rbi/hidden-definitions/hidden.rbi
- spec/support/v5.2/Gemfile.lock
- spec/support/v5.2/sorbet/rbi/hidden-definitions/hidden.rbi
- spec/support/v6.0/sorbet/rbi/hidden-definitions/hidden.rbi
sorbet has changed some provided rbi that breaks their own generated hidden-definitions. update hidden-definitions to make the test pass.
> fix sorbet tests

- README.md
I'm documenting this known issue to prevent people from opening
new issues.
> Docs: known issue re: class methods on Relation

- sorbet-rails.gemspec
Release a version with improved plugin configuration
> Bump version to 0.5.3

- lib/sorbet-rails/model_plugins/plugins.rb
We didn't add these to the list, oops.
https://github.com/chanzuckerberg/sorbet-rails/blob/d2037b25f3bad50716aa2d13eb707a835ee2d14f/lib/sorbet-rails/model_plugins/plugins.rb
> Add new gem plugins.

- CONTRIBUTING.md
I accidentally used `4.2` instead of `4_2` in the Rake commands in CONTRIBUTING.md
> Fix Rake tasks in CONTRIBUTING.md.

- lib/sorbet-rails/tasks/rails_rbi.rake
> Clean up bundled file

- lib/sorbet-rails/type_assert/type_assert.rb
- lib/sorbet-rails/type_assert/type_assert_impl.rb
- spec/support/v5.2/sorbet_test_cases.rb
The absolute measure:
```
return if $PROGRAM_NAME.include?('sorbet')
```
> fix hiding type_assert_impl from srb init

- sorbet-rails.gemspec
Some fixes & Boolean & IntegerString
> Bump 0.5.5.1

- README.md
- lib/sorbet-rails/gem_plugins/elastic_search_plugin.rb
- lib/sorbet-rails/gem_plugins/shrine_plugin.rb
- lib/sorbet-rails/model_plugins/plugins.rb
- lib/sorbet/rbi/todo.rbi
- Add the plugin. It's working in our own repo
- Add documentation
- We haven't set up tests yet, as it's arguably difficult to do. I guess we'll accept that the gem plugins are provided as-is, and YMMV when use them.
> Add shrine and elastic search plugin

- sorbet-rails.gemspec
I'm pretty sure this is going to fail in CI because the latest version of Sorbet didn't get released properly.
> Update Parlour to 1.0.

- lib/sorbet-rails/gem_plugins/kaminari_plugin.rb
See https://github.com/chanzuckerberg/sorbet-rails/pull/109#discussion_r349970367
There's a bunch more methods in https://github.com/kaminari/kaminari/blob/c5186f5d9b7f23299d115408e62047447fd3189d/kaminari-core/lib/kaminari/models/page_scope_methods.rb and https://github.com/kaminari/kaminari/blob/c5186f5d9b7f23299d115408e62047447fd3189d/kaminari-activerecord/lib/kaminari/activerecord/active_record_relation_methods.rb that could also be added. But these are the main ones, as per the docs: https://github.com/kaminari/kaminari#query-basics
> Add the other main Kaminari methods

- README.md
These came up as common errors while updating our internal Sorbet docs.
> Add a few more static attribute alternatives

- lib/bundled_rbi/active_record_relation.rbi
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/batches.rb#L67
> Add AR#find_each

- .gitattributes
The setting should make it easier to focus on actual code changes in PR view.
See the documentation here: https://github.com/github/linguist#vendored-code
> Add a linguist file to mark files as generated

- README.md
-  flattening Array of relation
- avoid `and_call_original` in spec
> Add 2 more tips

- lib/sorbet-rails/model_plugins/active_record_attribute.rb
Add better typing for array types to include the array subtype and also
fix the nullability. Unfortunately there is no easy way to add tests as
the current framework (understandably) uses SQLite for the DB engine
which does not support array types. I tested this with some of our data
models, however, and saw this worked properly:
sample `git diff` for table with `assignee_names` as `:string, array:
true`:
```
-  sig { returns(T::Array[T.nilable(T.untyped)]) }
+  sig { returns(T.nilable(T::Array[String])) }
def assignee_names; end
-  sig { params(value: T::Array[T.nilable(T.untyped)]).void }
+  sig { params(value: T.nilable(T::Array[T.any(String, Symbol)])).void }
def assignee_names=(value); end
```
Note that I only tested this on PostgreSQL so I'm unsure if this will fully work
on other …
> Improve array typing

- sorbet-rails.gemspec
- spec/support/v5.0/Gemfile.lock
- spec/support/v5.1/Gemfile.lock
- spec/support/v5.2/Gemfile.lock
- spec/support/v6.0/Gemfile.lock
Release a new version with some fixes for Rails 6
> release 0.6.5

- sorbet-rails.gemspec
- spec/support/v5.0/Gemfile.lock
- spec/support/v5.1/Gemfile.lock
- spec/support/v5.2/Gemfile.lock
- spec/support/v6.0/Gemfile.lock
Fix the return type of `in_batches`
> release 0.6.5.1

- spec/generators/sorbet_test_cases.rb
- spec/support/v5.0/sorbet_test_cases.rb
- spec/support/v5.1/sorbet_test_cases.rb
- spec/support/v5.2/sorbet_test_cases.rb
- spec/support/v6.0/sorbet_test_cases.rb
It should work when we set `Rails.application.routes.default_url_options`
> [url helper] Improve test to make it more realist

- lib/sorbet-rails/routes_rbi_formatter.rb
- spec/test_data/v5.0/expected_routes.rbi
- spec/test_data/v5.1/expected_routes.rbi
- spec/test_data/v5.2/expected_routes.rbi
- spec/test_data/v6.0/expected_routes.rbi
https://github.com/chanzuckerberg/sorbet-rails/issues/365
> add url helper to ActionController::API

- lib/sorbet-rails/model_plugins/active_record_assoc.rb
Reopen https://github.com/chanzuckerberg/sorbet-rails/pull/375
> Fix Plugin ActiveRecordAssoc undefined method oid for nil

- sorbet-rails.gemspec
- spec/support/v5.0/Gemfile.lock
- spec/support/v5.1/Gemfile.lock
- spec/support/v5.2/Gemfile.lock
- spec/support/v6.0/Gemfile.lock
> release version 0.7.3

- README.md
- lib/sorbet-rails/gem_plugins/attr_json_plugin.rb
- lib/sorbet-rails/model_plugins/plugins.rb
- sorbet/rbi/todo.rbi
Add plugin to [attr_json](https://github.com/jrochkind/attr_json) gem
Tested on our private repository.
> Add attr_json plugin

- lib/sorbet-rails/dependent_gem_rbis/parlour.rbi
- sorbet/rbi/gems/activerecord.rbi
- spec/rails_helper.rb
> fix DatabaseCleaner usage

- README.md
- lib/sorbet-rails/gem_plugins/flag_shih_tzu_plugin.rb
- lib/sorbet-rails/model_plugins/plugins.rb
- sorbet/rbi/todo.rbi
Add plugin to [flag_shih_tzu](https://github.com/pboling/flag_shih_tzu) gem.
Tested on our private repository.
> Add flag_shih_tzu plugin

- lib/sorbet-rails/model_column_utils.rb
- lib/sorbet-rails/model_plugins/active_record_assoc.rb
- spec/test_data/v5.2/expected_wizard_wo_spellbook.rbi
- spec/test_data/v6.0/expected_wizard_wo_spellbook.rbi
- spec/test_data/v6.1/expected_wizard_wo_spellbook.rbi
fixes #480 -- caused by sorbet/sorbet#5129
> fix T.nilable(T.untyped) errors with sorbet 0.5.9556
